'use strict';

export let KEYS = [
	{
		name_eng: '`',
		name_ru: 'ё',
		with_type: 'key-narrow1and5',
		shift_eng: '~',
		code: 'Backquote',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: '1',
		name_ru: '1',
		with_type: 'key-standart',
		shift: '!',
		code: 'Digit1',
		changeableShit: true,
	},
	{
		name: '2',
		with_type: 'key-standart',
		shift_eng: '@',
		shift_ru: '"',
		code: 'Digit2',
		changeableShit: true,
	},
	{
		name: '3',
		with_type: 'key-standart',
		shift_eng: '#',
		shift_ru: '№',
		code: 'Digit3',
		changeableShit: true,
	},
	{
		name: '4',
		with_type: 'key-standart',
		shift_eng: '$',
		shift_ru: ';',
		code: 'Digit4',
		changeableShit: true,
	},
	{
		name: '5',
		with_type: 'key-standart',
		shift: '%',
		code: 'Digit5',
		changeableShit: true,
	},
	{
		name: '6',
		with_type: 'key-standart',
		shift_eng: ':',
		shift_ru: '^',
		code: 'Digit6',
		changeableShit: true,
	},
	{
		name: '7',
		with_type: 'key-standart',
		shift_eng: '?',
		shift_ru: '&',
		code: 'Digit7',
		changeableShit: true,
	},
	{
		name: '8',
		with_type: 'key-standart',
		shift: '*',
		code: 'Digit8',
		changeableShit: true,
	},
	{
		name: '9',
		with_type: 'key-standart',
		shift: '(',
		code: 'Digit9',
		changeableShit: true,
	},
	{
		name: '0',
		with_type: 'key-standart',
		shift: ')',
		code: 'Digit0',
		changeableShit: true,
	},
	{
		name: '-',
		with_type: 'key-standart',
		shift: '_',
		code: 'Minus',
		changeableShit: true,
	},
	{
		name: '=',
		with_type: 'key-standart',
		shift: '+',
		code: 'Equal',
		changeableShit: true,
	},
	{
		name: 'Backspace',
		with_type: 'key-wide2',
		code: 'Backspace'
	},
	{
		name: 'Tab',
		with_type: 'key-wide1and5',
		code: 'Tab'
	},
	{
		name_eng: 'q',
		name_ru: 'й',
		with_type: 'key-standart',
		code: 'KeyQ',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'w',
		name_ru: 'ц',
		with_type: 'key-standart',
		code: 'KeyW',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'e',
		name_ru: 'у',
		with_type: 'key-standart',
		code: 'KeyE',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'r',
		name_ru: 'к',
		with_type: 'key-standart',
		code: 'KeyR',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 't',
		name_ru: 'е',
		with_type: 'key-standart',
		code: 'KeyT',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'y',
		name_ru: 'н',
		with_type: 'key-standart',
		code: 'KeyY',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'u',
		name_ru: 'г',
		with_type: 'key-standart',
		code: 'KeyU',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'i',
		name_ru: 'ш',
		with_type: 'key-standart',
		code: 'KeyI',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'o',
		name_ru: 'щ',
		with_type: 'key-standart',
		code: 'KeyO',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'p',
		name_ru: 'з',
		with_type: 'key-standart',
		shift_eng: '?',
		shift_ru: '&',
		code: 'KeyP',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: '[',
		name_ru: 'х',
		with_type: 'key-standart',
		shift_eng: '{',
		code: 'BracketLeft',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: ']',
		name_ru: 'ъ',
		with_type: 'key-standart',
		shift_eng: '}',
		code: 'BracketRight',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name: '\\',
		with_type: 'key-standart',
		shift_eng: '|',
		shift_ru: '/',
		code: 'Backslash',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name: 'Caps Lock',
		with_type: 'key-wide2',
		code: 'CapsLock'
	},
	{
		name_eng: 'a',
		name_ru: 'ф',
		with_type: 'key-standart',
		code: 'KeyA',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 's',
		name_ru: 'ы',
		with_type: 'key-standart',
		code: 'KeyS',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'd',
		name_ru: 'в',
		with_type: 'key-standart',
		code: 'KeyD',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'f',
		name_ru: 'а',
		with_type: 'key-standart',
		code: 'KeyF',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'g',
		name_ru: 'п',
		with_type: 'key-standart',
		code: 'KeyG',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'h',
		name_ru: 'р',
		with_type: 'key-standart',
		code: 'KeyH',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'j',
		name_ru: 'л',
		with_type: 'key-standart',
		code: 'KeyJ',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'k',
		name_ru: 'л',
		with_type: 'key-standart',
		code: 'KeyK',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'l',
		name_ru: 'д',
		with_type: 'key-standart',
		code: 'KeyL',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: ';',
		name_ru: 'ж',
		with_type: 'key-standart',
		shift_eng: ':',
		code: 'Semicolon',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: '\'',
		name_ru: 'э',
		with_type: 'key-standart',
		shift_eng: '"',
		code: 'Quote',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name: 'Enter',
		with_type: 'key-wide2',
		code: 'Enter'
	},
	{
		name: 'Shift',
		with_type: 'key-wide2',
		code: 'ShiftLeft'
	},
	{
		name_eng: 'z',
		name_ru: 'я',
		with_type: 'key-standart',
		code: 'KeyZ',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'x',
		name_ru: 'ч',
		with_type: 'key-standart',
		code: 'KeyX',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'c',
		name_ru: 'с',
		with_type: 'key-standart',
		code: 'KeyC',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'v',
		name_ru: 'м',
		with_type: 'key-standart',
		code: 'KeyV',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'b',
		name_ru: 'и',
		with_type: 'key-standart',
		code: 'KeyB',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'n',
		name_ru: 'т',
		with_type: 'key-standart',
		code: 'KeyN',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: 'm',
		name_ru: 'ь',
		with_type: 'key-standart',
		code: 'KeyM',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: ',',
		name_ru: 'б',
		with_type: 'key-standart',
		shift_eng: '<',
		code: 'Comma',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name_eng: '.',
		name_ru: 'ю',
		with_type: 'key-standart',
		shift_eng: '>',
		code: 'Period',
		changeableLanguage: true,
		changeableShit: true,

	},
	{
		name_eng: '/',
		name_ru: '.',
		with_type: 'key-standart',
		shift_eng: '?',
		shift_ru: ',',
		code: 'Slash',
		changeableLanguage: true,
		changeableShit: true,
	},
	{
		name: '&uarr;',
		with_type: 'key-standart',
		code: 'ArrowUp'
	},
	{
		name: 'Del',
		with_type: 'key-wide2',
		code: 'Delete'
	},
	{
		name: 'Ctrl',
		with_type: 'key-standart',
		code: 'ControlLeft'
	},
	{
		name: 'Win',
		with_type: 'key-standart',
		code: 'MetaLeft'
	},
	{
		name_eng: 'ENG',
		name_ru: 'RU',
		with_type: 'key-standart',
		changeableLanguage: true,
	},
	{
		name: 'Alt',
		with_type: 'key-standart',
		code: 'AltLeft'
	},
	{
		name: 'Space',
		with_type: 'key-wide5',
		code: 'Space'
	},
	{
		name: 'Alt',
		with_type: 'key-standart',
		code: 'AltRight'
	},
	{
		name: 'Ctrl',
		with_type: 'key-standart',
		code: 'ControlRight'
	},
	{
		name: '&larr;',
		with_type: 'key-standart',
		code: 'ArrowLeft'
	},
	{
		name: '&darr;',
		with_type: 'key-standart',
		code: 'ArrowDown'
	},
	{
		name: '&rarr;',
		with_type: 'key-standart',
		code: 'ArrowRight'
	},
	{
		name: 'Shift',
		with_type: 'key-standart',
		code: 'ShiftRight'
	},
];